using FinanzasPersonales.Database;
using FinanzasPersonales.Models;
using FinanzasPersonales.Services;
using Microsoft.Extensions.Configuration;
using MongoDB.Driver;
using Moq;
using System;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using Xunit;

namespace FinanzasPersonales.Tests.Services
{
    public class UsuarioServiceTests
    {
        private readonly Mock<IMongoCollection<Usuario>> _mockCollection;
        private readonly Mock<IMongoDBContext> _mockContext;
        private readonly Mock<IConfiguration> _mockConfig;
        private readonly UsuarioService _service;

        public UsuarioServiceTests()
        {
            _mockCollection = new Mock<IMongoCollection<Usuario>>();
            _mockContext = new Mock<IMongoDBContext>();
            _mockConfig = new Mock<IConfiguration>();

            _mockContext.Setup(c => c.Usuarios).Returns(_mockCollection.Object);

            _mockConfig.Setup(c => c["Jwt:Key"]).Returns("test_jwt_key_which_is_long_enough_1234567890");
            _mockConfig.Setup(c => c["Jwt:Issuer"]).Returns("test_issuer");
            _mockConfig.Setup(c => c["Jwt:Audience"]).Returns("test_audience");

            _service = new UsuarioService(_mockContext.Object, _mockConfig.Object);
        }

        [Fact]
        public async Task RegisterAsync_InsertsNewUser()
        {
            // Arrange: Find should return null (no existing user)
        var mockCursor = new Mock<IAsyncCursor<Usuario>>();
        mockCursor.SetupGet(c => c.Current).Returns(new List<Usuario>());
        mockCursor.SetupSequence(c => c.MoveNextAsync(It.IsAny<CancellationToken>()))
                  .ReturnsAsync(true)
                  .ReturnsAsync(false);

        _mockCollection
            .Setup(c => c.FindAsync(
                It.IsAny<FilterDefinition<Usuario>>(),
                It.IsAny<FindOptions<Usuario, Usuario>>(),
                It.IsAny<CancellationToken>()
            ))
            .ReturnsAsync(mockCursor.Object);

        Usuario? captured = null;
        _mockCollection.Setup(c => c.InsertOneAsync(It.IsAny<Usuario>(), null, It.IsAny<CancellationToken>()))
               .Callback<Usuario, InsertOneOptions, CancellationToken>((u, o, t) => captured = u)
               .Returns(Task.CompletedTask);

            // Act
            var result = await _service.RegisterAsync(" TestUser ", "Password123");

            // Assert
            Assert.NotNull(result);
            Assert.Equal("testuser", result.Username);
            Assert.False(result.IsActive);
            Assert.Equal("usuario", result.Role);
            Assert.NotNull(result.PasswordHash);
            Assert.Contains(":", result.PasswordHash);
            _mockCollection.Verify(c => c.InsertOneAsync(It.IsAny<Usuario>(), null, It.IsAny<CancellationToken>()), Times.Once);
        }

        [Fact]
        public async Task RegisterAsync_Throws_WhenUserExists()
        {
            // Arrange: Find returns an existing user
            var existing = new Usuario { Id = "1", Username = "testuser" };
            var mockCursor = new Mock<IAsyncCursor<Usuario>>();
            mockCursor.SetupGet(c => c.Current).Returns(new List<Usuario> { existing });
            mockCursor.SetupSequence(c => c.MoveNextAsync(It.IsAny<CancellationToken>()))
                      .ReturnsAsync(true)
                      .ReturnsAsync(false);

            _mockCollection
                .Setup(c => c.FindAsync(
                    It.IsAny<FilterDefinition<Usuario>>(),
                    It.IsAny<FindOptions<Usuario, Usuario>>(),
                    It.IsAny<CancellationToken>()
                ))
                .ReturnsAsync(mockCursor.Object);

            // Act & Assert
            await Assert.ThrowsAsync<InvalidOperationException>(() => _service.RegisterAsync("testuser", "pwd"));
        }

        [Theory]
        [InlineData("")]
        [InlineData("   ")]
        public async Task RegisterAsync_Throws_OnEmptyUsername(string username)
        {
            // Act & Assert
            await Assert.ThrowsAsync<ArgumentException>(() => _service.RegisterAsync(username, "pwd"));
        }

        [Fact]
        public async Task LoginAsync_ReturnsToken_ForValidCredentials()
        {
            // Arrange: create a stored user with password hash generated by the service
            var pwd = "SecretPwd!23";
            // Use the internal HashPassword directly (InternalsVisibleTo provided)
            var storedHash = _service.HashPassword(pwd);

            var storedUser = new Usuario { Id = "u1", Username = "testuser", PasswordHash = storedHash, IsActive = true, Role = "usuario" };

            var mockCursor = new Mock<IAsyncCursor<Usuario>>();
            mockCursor.SetupGet(c => c.Current).Returns(new List<Usuario> { storedUser });
            mockCursor.SetupSequence(c => c.MoveNextAsync(It.IsAny<CancellationToken>()))
                      .ReturnsAsync(true)
                      .ReturnsAsync(false);

            _mockCollection
                .Setup(c => c.FindAsync(
                    It.IsAny<FilterDefinition<Usuario>>(),
                    It.IsAny<FindOptions<Usuario, Usuario>>(),
                    It.IsAny<CancellationToken>()
                ))
                .ReturnsAsync(mockCursor.Object);

            // Act
            var token = await _service.LoginAsync(" TestUser ", pwd);

            // Assert
            Assert.False(string.IsNullOrWhiteSpace(token));
            Assert.Contains('.', token);

            // Validate token contains expected claims
            var jwt = new System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler().ReadJwtToken(token);
            Assert.Equal("testuser", jwt.Claims.First(c => c.Type == System.IdentityModel.Tokens.Jwt.JwtRegisteredClaimNames.UniqueName).Value);
            Assert.Equal("u1", jwt.Claims.First(c => c.Type == System.IdentityModel.Tokens.Jwt.JwtRegisteredClaimNames.Sub).Value);
            Assert.Equal("usuario", jwt.Claims.First(c => c.Type == System.Security.Claims.ClaimTypes.Role).Value);
        }

        [Fact]
        public async Task LoginAsync_Throws_WhenUserNotFound()
        {
            // Arrange: Find returns null
            var mockCursor = new Mock<IAsyncCursor<Usuario>>();
            mockCursor.SetupGet(c => c.Current).Returns(new List<Usuario>());
            mockCursor.SetupSequence(c => c.MoveNextAsync(It.IsAny<CancellationToken>()))
                      .ReturnsAsync(false);

            _mockCollection
                .Setup(c => c.FindAsync(
                    It.IsAny<FilterDefinition<Usuario>>(),
                    It.IsAny<FindOptions<Usuario, Usuario>>(),
                    It.IsAny<CancellationToken>()
                ))
                .ReturnsAsync(mockCursor.Object);

            // Act & Assert
            await Assert.ThrowsAsync<UnauthorizedAccessException>(() => _service.LoginAsync("noone", "pwd"));
        }

        [Fact]
        public async Task LoginAsync_Throws_WhenPasswordEmpty()
        {
            // Arrange: create stored user with a real hash
            var pwd = "RealPwd1!";
            var storedHash = _service.HashPassword(pwd);
            var storedUser = new Usuario { Id = "ux", Username = "testuser", PasswordHash = storedHash, IsActive = true };

            var mockCursor = new Mock<IAsyncCursor<Usuario>>();
            mockCursor.SetupGet(c => c.Current).Returns(new List<Usuario> { storedUser });
            mockCursor.SetupSequence(c => c.MoveNextAsync(It.IsAny<CancellationToken>()))
                      .ReturnsAsync(true)
                      .ReturnsAsync(false);

            _mockCollection
                .Setup(c => c.FindAsync(
                    It.IsAny<FilterDefinition<Usuario>>(),
                    It.IsAny<FindOptions<Usuario, Usuario>>(),
                    It.IsAny<CancellationToken>()
                ))
                .ReturnsAsync(mockCursor.Object);

            // Act & Assert: empty password should be rejected
            await Assert.ThrowsAsync<UnauthorizedAccessException>(() => _service.LoginAsync("testuser", ""));
        }

        [Fact]
        public async Task LoginAsync_Throws_WhenUserNotActive()
        {
            // Arrange: Found but not active
            var pwd = "Pwd123";
            var storedHash2 = _service.HashPassword(pwd);

            var storedUser2 = new Usuario { Id = "u2", Username = "testuser", PasswordHash = storedHash2, IsActive = false };

            var mockCursor2 = new Mock<IAsyncCursor<Usuario>>();
            mockCursor2.SetupGet(c => c.Current).Returns(new List<Usuario> { storedUser2 });
            mockCursor2.SetupSequence(c => c.MoveNextAsync(It.IsAny<CancellationToken>()))
                       .ReturnsAsync(true)
                       .ReturnsAsync(false);

            _mockCollection
                .Setup(c => c.FindAsync(
                    It.IsAny<FilterDefinition<Usuario>>(),
                    It.IsAny<FindOptions<Usuario, Usuario>>(),
                    It.IsAny<CancellationToken>()
                ))
                .ReturnsAsync(mockCursor2.Object);

            // Act & Assert
            var ex = await Assert.ThrowsAsync<UnauthorizedAccessException>(() => _service.LoginAsync("testuser", pwd));
            Assert.Contains("activado", ex.Message);
        }

        [Fact]
        public async Task IsActiveAsync_ReturnsTrueOrFalse()
        {
            // Arrange true
            var storedUser = new Usuario { Username = "testuser", IsActive = true };
            var mockCursor = new Mock<IAsyncCursor<Usuario>>();
            mockCursor.SetupGet(c => c.Current).Returns(new List<Usuario> { storedUser });
            mockCursor.SetupSequence(c => c.MoveNextAsync(It.IsAny<CancellationToken>()))
                      .ReturnsAsync(true)
                      .ReturnsAsync(false);

            _mockCollection
                .Setup(c => c.FindAsync(
                    It.IsAny<FilterDefinition<Usuario>>(),
                    It.IsAny<FindOptions<Usuario, Usuario>>(),
                    It.IsAny<CancellationToken>()
                ))
                .ReturnsAsync(mockCursor.Object);

            // Act
            var isActive = await _service.IsActiveAsync("testuser");

            // Assert
            Assert.True(isActive);

            // Arrange false
            var mockCursor3 = new Mock<IAsyncCursor<Usuario>>();
            mockCursor3.SetupGet(c => c.Current).Returns(new List<Usuario>());
            mockCursor3.SetupSequence(c => c.MoveNextAsync(It.IsAny<CancellationToken>()))
                       .ReturnsAsync(false);

            _mockCollection
                .Setup(c => c.FindAsync(
                    It.IsAny<FilterDefinition<Usuario>>(),
                    It.IsAny<FindOptions<Usuario, Usuario>>(),
                    It.IsAny<CancellationToken>()
                ))
                .ReturnsAsync(mockCursor3.Object);

            // Act
            var isActive2 = await _service.IsActiveAsync("other");
            Assert.False(isActive2);
        }
    }
}
